### ISSUE TITLE
check_interrupts = TRUE causes certain query with inner join to fail with error message "select() on the connection failed"

### ISSUE THREAD

**Issue by LaugeGregers** [r-dbi/RPostgres#244] opened 2020-04-21 14:09 UTC
The following query, when run through `dbGetQuery()` fails when using `check_interupts = TRUE` in `dbConnect()`. Error message is "select() on the connection failed"

```SQL
select dsc.dw_customer_key
from dws_customer dsc
inner join tmp_20200420_customer_reg_dates_2019 tmp 
  on tmp.dw_customer_key = dsc.dw_customer_key
where 1 = 1 and dsc.dw_distribution_key between 201902 * 1337 and 201903 * 1337
limit 10
```

The queries are run against my company's Data warehouse. 

Queries including only one of the tables `dws_customer` or `tmp_20200420_customer_reg_dates_2019` work. Queries with other inner joins work fine.

```r
bad_query <- "select dsc.dw_customer_key
from dws_customer dsc
inner join tmp_20200420_customer_reg_dates_2019 tmp 
  on tmp.dw_customer_key = dsc.dw_customer_key
where 1 = 1 and dsc.dw_distribution_key between 201902 * 1337 and 201903 * 1337
limit 10"

# Shows that we can fetch from dws_customer
working_query <- "select dsc.dw_customer_key 
from dws_customer dsc 
limit 10"

# Shows that we can fetch from tmp_20200420_customer_reg_dates_2019
working_query2 <- "select tmp.dw_customer_key
from tmp_20200420_customer_reg_dates_2019 tmp
limit 10"

# shows that we can do inner joins 
working_query3 <- "select 
  dfc.dw_contact_event_key, 
  ddc.external_info1_description
from dwf_contact dfc
inner join dwd_contact_event ddc 
    on ddc.dw_contact_event_key = dfc.dw_contact_event_key
limit 10"

library(DBI)

# Following fails on last query
tmp_con <- 
  dbConnect(RPostgres::Postgres(),
            dbname = "dw_db",
            host = "company DW", 
            port = "proper port", 
            user = "foobar", 
            password = "foobar",
            check_interrupts = TRUE)
dbGetQuery(tmp_con, working_query)
dbGetQuery(tmp_con, working_query2)
dbGetQuery(tmp_con, working_query3)
dbGetQuery(tmp_con, bad_query) # Error: select() on the connection failed
dbDisconnect(tmp_con)
```

Changing the order in which queries are run, doesn't change the result. 

If we set `check_interrupts = FALSE` the query works. The others work as well.

```r
# Following works
tmp_con2 <- 
  dbConnect(RPostgres::Postgres(),
            dbname = "dw_db",
            host = "company DW", 
            port = "proper port", 
            user = "foobar", 
            password = "foobar",
            check_interrupts = FALSE)
dbGetQuery(tmp_con2, working_query)
dbGetQuery(tmp_con2, working_query2)
dbGetQuery(tmp_con2, working_query3)
dbGetQuery(tmp_con2, bad_query)
dbDisconnect(tmp_con2)
```

All four queries work under RPostgreSQL as well.

**EDIT:**

Having done a bit more investigation, I have found some more bugs/weird behaviour.

If I remove the condition in `bad_query` it runs fine. Some times `working_query` also fails with `"Error: select() on the connection failed"` when it is run as the first query of an open connection, but not all the time. 

The two tables `dws_customer` and `tmp_20200420_customer_reg_dates_2019` lie in two different schemas, but this doesn't seem to be the culprit, as I am able to join other tables from the two schemas. 

The error also appears with `check_interrupts = TRUE` when I construct a query that returns 0 rows. Using `check_interrupts = FALSE` I get a data.frame of 0 rows with the appropriate columns.

**Comment by krlmlr** [comment] 2020-12-26 05:17
Thanks for the detailed report.

@zozlak: Could you please take a look?

**Comment by zozlak** [comment] 2020-12-29 16:33
This is a very low-level issue with TCP/IP communication being raised [here](https://github.com/r-dbi/RPostgres/blob/master/src/PqResultImpl.cpp#L493-L499). Actual SQL query has (almost) for sure nothing to do with it. What can exactly go wrong is listed [here](https://man7.org/linux/man-pages/man2/select.2.html#ERRORS) but unfortunately I haven't included the error code in the [error message](https://github.com/r-dbi/RPostgres/blob/master/src/PqResultImpl.cpp#L498).

To investigate it I would need to grab the exact error code, the `FD_SETSIZE` and `socket` number.
As I guess the issue is rather platform-specific I would need @LaugeGregers to build a little adjusted package code from source and run the failing queries again. @LaugeGregers what operating system are you using and are you familiar with building an R package from source?

Also, what is your R and Postgresql (both client and server) version?

**Comment by iangow** [comment] 2021-03-31 02:05
@zozlak If it helps, I'm seeing this issue (from two users) on Windows, but not Ubuntu or MacOS.

**Comment by zozlak** [comment] 2021-03-31 08:28
@iangow this points us into the direction of `FD_SETSIZE` but again - to solve it I need someone able to a) replicate the error b) build and run adjusted package code. Do you know anyone?

**Comment by iangow** [comment] 2021-04-05 12:43
> @iangow this points us into the direction of `FD_SETSIZE` but again - to solve it I need someone able to a) replicate the error b) build and run adjusted package code. Do you know anyone?

I don't have access to Windows, but if the task is not more complicated than (say) perhaps running `devtools::install_github` and some test code, then I can ask a colleague to help. (I think reproducing the error shouldn't be difficult.)

**Comment by zozlak** [comment] 2021-04-05 16:26
> is not more complicated than (say) perhaps running devtools::install_github 

I'm afraid it is but as I'm not using Windows and not building R packages under Windows, I can't tell exactly. @krlmlr can you tell use what's needed to build RPostgres under Windows (besides a vanilla R installation)?

**Comment by krlmlr** [comment] 2021-04-05 16:32
Only Rtools AFAICT, get it from https://cran.r-project.org/bin/windows/Rtools/. Everything else (including libpq) should work out of the box.

**Comment by zozlak** [comment] 2021-04-05 16:54
Ok, it doesn't sound bad. I will prepare a debugging branch this week.

**Comment by iangow** [comment] 2021-04-05 23:30
> Ok, it doesn't sound bad. I will prepare a debugging branch this week.

I have asked my Windows colleague to check that he can install from GitHub. Once confirmed and you have prepared the debugging branch, I can set him up with a simple version of the code that wasn't working and get it tested. Thanks.

**Comment by zozlak** [comment] 2021-04-06 06:27
So here we go:

* Install the [Rtools](https://cran.r-project.org/bin/windows/Rtools/)
* Install the devtools (`install.packages('devtools')`)
* Install RPostgres with `devtools::install_github('https://github.com/zozlak/RPostgres', ref = 'issue-244')`
* Replicate the error. Now the error message should look like "select() on the connection socket 17 (FD_SETSIZE 1024) failed with error code 8" (of course with different numbers). Please provide the exact error message.

**Comment by iangow** [comment] 2021-04-16 14:13
I remembered I had a copy of Windows installed in a VM on my Ubuntu box nearby. So I tried this myself. 

I added a couple of steps before the third step above:

- `remove.packages("RPostgres", lib="~/R/win-library/4.0")`.
- `Sys.setenv(R_INSTALL_STAGED = FALSE)` (see [here](https://stackoverflow.com/questions/56615734/r-package-ps-fails-to-install-because-permission-denied-to-mv-in-final-step-of))

For now I am hitting another issue to do with `without_tz`. **If you have any suggestion for how I might side-step that, I could try again.**

1. Original code with current CRAN package:

(This isn't the best code perhaps, but simpler code did not trigger the issue, so I stuck with this.)

``` r
library(dplyr, warn.conflicts = FALSE)
library(DBI)

pg <- dbConnect(RPostgres::Postgres(),
                bigint = "integer",
                check_interrupts = TRUE)

fundq <- tbl(pg, sql("SELECT * FROM comp.fundq"))

fundq_mod <-
  fundq %>%
  filter(indfmt == "INDL", datafmt == "STD",
         consol == "C", popsrc == "D")

fundq_mod %>%
  group_by(gvkey, datadate) %>%
  summarize(num_rows = n(), .groups = "drop") %>%
  count(num_rows)
#> Error: select() on the connection failed
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

2. Same CRAN package, but with `check_interrupts=FALSE`:

``` r
library(dplyr, warn.conflicts = FALSE)
library(DBI)

pg <- dbConnect(RPostgres::Postgres(),
                bigint = "integer",
                check_interrupts = TRUE)

fundq <- tbl(pg, sql("SELECT * FROM comp.fundq"))

fundq_mod <-
  fundq %>%
  filter(indfmt == "INDL", datafmt == "STD",
         consol == "C", popsrc == "D")

fundq_mod %>%
  group_by(gvkey, datadate) %>%
  summarize(num_rows = n(), .groups = "drop") %>%
  count(num_rows)
#> Error: select() on the connection failed
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

3. Once more, but with GitHub package and `check_interrupts=TRUE`:

``` r
library(dplyr, warn.conflicts = FALSE)
library(DBI)

pg <- dbConnect(RPostgres::Postgres(),
                bigint = "integer",
                check_interrupts = TRUE)
#> Error in which(attr(ret, "without_tz")): argument to 'which' is not logical

fundq <- tbl(pg, sql("SELECT * FROM comp.fundq"))
#> Error in tbl(pg, sql("SELECT * FROM comp.fundq")): object 'pg' not found

fundq_mod <-
  fundq %>%
  filter(indfmt == "INDL", datafmt == "STD",
         consol == "C", popsrc == "D")
#> Error in filter(., indfmt == "INDL", datafmt == "STD", consol == "C", : object 'fundq' not found

fundq_mod %>%
  group_by(gvkey, datadate) %>%
  summarize(num_rows = n(), .groups = "drop") %>%
  count(num_rows)
#> Error in group_by(., gvkey, datadate): object 'fundq_mod' not found
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by zozlak** [comment] 2021-04-16 17:41
Clearly something went wrong already in `DBI::dbConnect()`. Unfortunately I can't reproduce. You made me curious and I even found a Windows machine, installed R and RTools on it and run:

```R
install.packages('devtools')
devtools::install_github('https://github.com/zozlak/RPostgres', ref = 'issue-244')
con = DBI::dbConnect(
  RPostgres::Postgres(), 
  host = '127.0.0.1', user = '***', dbname = '***', password = '***', 
  check_interrupts = TRUE, bigint = "integer"
)
DBI::dbGetQuery(con, "doesn't really matter as it's database structure-specific but I made an inner join there just to be in line with this issue description")

install.packages(c('dbplyr', 'dplyr'))
library(dplyr)
tab = tbl(con, sql("SELECT * FROM teryt_gminy"))
tab %>% group_by(id_gminy) %>% summarize(n = n())
```

but in both cases just got a proper output.

Unfortunately this doesn't bring us any closer as:

* It looks like you hit some other issue while trying to use the version you installed from the github.
* This error is not as deterministic as we would like it to be.

Anyway once I have access to a Windows machine with a ready to debugging RPostgres package version being installed the only (ha, ha!) thing which I lack is access to adatabase and knowledge of an SQL query which would allow me to reproduce the error. The second one is easy but how to deal with the database part?

**Comment by iangow** [comment] 2021-04-16 18:16
@zozlak I sent you some connection information. With that you should be able to run this test code (it works here because I'm running from MacOS):

``` r
library(dplyr, warn.conflicts = FALSE)
library(DBI)

pg <- dbConnect(RPostgres::Postgres(),
                bigint = "integer",
                check_interrupts = TRUE)

fundq <- tbl(pg, sql("SELECT * FROM comp.fundq"))

fundq_mod <-
  fundq %>%
  filter(indfmt == "INDL", datafmt == "STD",
         consol == "C", popsrc == "D")

fundq_mod %>%
  group_by(gvkey, datadate) %>%
  summarize(num_rows = n(), .groups = "drop") %>%
  count(num_rows) %>%
  collect()
#> # A tibble: 2 x 2
#>   num_rows       n
#>      <int>   <int>
#> 1        2    1450
#> 2        1 1842654
```

<sup>Created on 2021-04-16 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by iangow** [comment] 2021-04-16 18:17
@zozlak If that code works for you on Windows, I could try to make sure that my Windows setup parallels yours and hopefully we can narrow this down. Thanks.

**Comment by zozlak** [comment] 2021-04-16 19:36
@iangow great, I was able to replicate:

```r
> fundq_mod %>%
+   group_by(gvkey, datadate) %>%
+   summarize(num_rows = n(), .groups = "drop") %>%
+   count(num_rows) %>%
+   collect()
Error: select() on the connection socket 1476 (FD_SETSIZE 64) failed with error code -1
```

Moreover, the error is clear:

* from glibc `select()` manual "select() can monitor only file descriptors numbers that are less than FD_SETSIZE"
* `FD_SETSIZE` is 64, socket descriptor number is 1476, `select()` can monitor it

Based on the glibc `select()` manual, `poll()` or `epoll()` which doesn't have such a limitation should be used instead. I will take a look.

**Comment by zozlak** [comment] 2021-04-16 21:47
It turned out on Windows things work differently:

* The `FD_SETSIZE` has completely different meaning and is not an issue.
* Errors are reported by a dedicated function (`WSAGetLastError()`).
* The `fd_set` structure has to be initialized (the `FD_SET()` macro has to be called) before every call to `select()` (similarly to the `timeval` struct requiring reinitialization on Linux). By the way - am I blind, is it to late or maybe it's not mentioned [in the documentation](https://docs.microsoft.com/pl-pl/windows/win32/api/winsock2/nf-winsock2-select)?

Anyway the solution seems clear, it seems to work and during the weekend I will prepare a pull request.

**Comment by krlmlr** [comment] 2021-08-24 02:31
Fixed now.

**Closed by krlmlr** 2021-08-24 02:31 UTC
