### ISSUE TITLE
dbWriteTable with copy = FALSE and sqlAppendTable do not work correctly with character

### ISSUE THREAD

**Issue by mgirlich** [r-dbi/RPostgres#234] opened 2019-12-09 06:52 UTC
Character columns are not escaped and therefore invalid SQL is produced.

```r
DBI::sqlAppendTable(
  con, "test",
  data.frame(a = "a", stringsAsFactors = FALSE),
  row.names = FALSE
)

# <SQL> INSERT INTO "test"
#   ("a")
# VALUES
#   (a)
```

**Comment by krlmlr** [comment] 2019-12-17 21:34
Thanks. Can you append with `dbAppendTable()` ?

**Comment by krlmlr** [comment] 2019-12-17 21:50
Closing as duplicate of #209.

**Closed by krlmlr** 2019-12-17 21:50 UTC
