### ISSUE TITLE
dbWriteTable() sets numeric fields as type 'real' when using RPostgres

### ISSUE THREAD

**Issue by ljvillanueva** [r-dbi/RPostgres#225] opened 2019-08-07 13:33 UTC
dbWriteTable() sets numeric fields as type `real` when it creates the table in Postgresql when using Rpostgres. When using the ODBC driver, fields were saved to a `double precision` type.

Using RPostgres:

```r
library(DBI)
library(RPostgres)
#> Warning: package 'RPostgres' was built under R version 3.5.3

setwd("E:/scripts/NMAH/xgview")

#database creds
source("settings_db.R")

#Connect to the database ----
con <- dbConnect(RPostgres::Postgres(), 
                 dbname = pg_db, 
                 host = pg_host, 
                 port = 5432, 
                 user = pg_user, 
                 password = pg_pass)

data_df <- data.frame(id = 123, value1 = 456.45, value2 = "test_id2", stringsAsFactors = FALSE)

class(data_df$id)
#> [1] "numeric"
class(data_df$value1)
#> [1] "numeric"
class(data_df$value2)
#> [1] "character"

dbWriteTable(con, "data_df", data_df, overwrite = TRUE, append = FALSE)

dbGetQuery(con, "SELECT pg_typeof(id) as id_type, pg_typeof(value1) as id1_type, pg_typeof(value2) as id2_type FROM data_df")
#>   id_type id1_type id2_type
#> 1    real     real     text
```

Using ODBC Driver:

```r
library(DBI)

setwd("E:/scripts/")

#database creds
source("settings_db.R")

#Connect to the database ----
con <- dbConnect(odbc::odbc(),
                 driver = "PostgreSQL Unicode(x64)",
                 database = pg_db,
                 uid = pg_user,
                 pwd = pg_pass,
                 host = pg_host,
                 port = 5432)

data_df <- data.frame(id = 123, value1 = 456.45, value2 = "test_id2", stringsAsFactors = FALSE)

class(data_df$id)
#> [1] "numeric"
class(data_df$value1)
#> [1] "numeric"
class(data_df$value2)
#> [1] "character"

dbWriteTable(con, "data_df", data_df, overwrite = TRUE, append = FALSE)

dbGetQuery(con, "SELECT pg_typeof(id) as id_type, pg_typeof(value1) as id1_type, pg_typeof(value2) as id2_type FROM data_df")
#>            id_type         id1_type id2_type
#> 1 double precision double precision     text

```

Database: PostgreSQL 10.9 (Ubuntu 10.9-1.pgdg18.04+1) on Ubuntu 18.04.3

session_info():

```r
library(DBI)
library(RPostgres)
#> Warning: package 'RPostgres' was built under R version 3.5.3
devtools::session_info()
#> - Session info ----------------------------------------------------------
#>  setting  value                       
#>  version  R version 3.5.1 (2018-07-02)
#>  os       Windows 10 x64              
#>  system   x86_64, mingw32             
#>  ui       RTerm                       
#>  language (EN)                        
#>  collate  English_United States.1252  
#>  ctype    English_United States.1252  
#>  tz       America/New_York            
#>  date     2019-08-07                  
#> 
#> - Packages --------------------------------------------------------------
#>  package     * version date       lib source        
#>  assertthat    0.2.1   2019-03-21 [1] CRAN (R 3.5.3)
#>  backports     1.1.4   2019-04-10 [1] CRAN (R 3.5.3)
#>  bit           1.1-14  2018-05-29 [1] CRAN (R 3.5.0)
#>  bit64         0.9-7   2017-05-08 [1] CRAN (R 3.5.0)
#>  blob          1.2.0   2019-07-09 [1] CRAN (R 3.5.3)
#>  callr         3.3.1   2019-07-18 [1] CRAN (R 3.5.3)
#>  cli           1.1.0   2019-03-19 [1] CRAN (R 3.5.3)
#>  crayon        1.3.4   2017-09-16 [1] CRAN (R 3.5.1)
#>  DBI         * 1.0.0   2018-05-02 [1] CRAN (R 3.5.1)
#>  desc          1.2.0   2018-05-01 [1] CRAN (R 3.5.3)
#>  devtools      2.1.0   2019-07-06 [1] CRAN (R 3.5.3)
#>  digest        0.6.20  2019-07-04 [1] CRAN (R 3.5.3)
#>  evaluate      0.14    2019-05-28 [1] CRAN (R 3.5.1)
#>  fs            1.3.1   2019-05-06 [1] CRAN (R 3.5.3)
#>  glue          1.3.1   2019-03-12 [1] CRAN (R 3.5.3)
#>  highr         0.8     2019-03-20 [1] CRAN (R 3.5.3)
#>  hms           0.5.0   2019-07-09 [1] CRAN (R 3.5.3)
#>  htmltools     0.3.6   2017-04-28 [1] CRAN (R 3.5.1)
#>  knitr         1.23    2019-05-18 [1] CRAN (R 3.5.3)
#>  magrittr      1.5     2014-11-22 [1] CRAN (R 3.5.1)
#>  memoise       1.1.0   2017-04-21 [1] CRAN (R 3.5.1)
#>  pillar        1.4.2   2019-06-29 [1] CRAN (R 3.5.3)
#>  pkgbuild      1.0.4   2019-08-05 [1] CRAN (R 3.5.1)
#>  pkgconfig     2.0.2   2018-08-16 [1] CRAN (R 3.5.3)
#>  pkgload       1.0.2   2018-10-29 [1] CRAN (R 3.5.3)
#>  prettyunits   1.0.2   2015-07-13 [1] CRAN (R 3.5.1)
#>  processx      3.4.1   2019-07-18 [1] CRAN (R 3.5.3)
#>  ps            1.3.0   2018-12-21 [1] CRAN (R 3.5.3)
#>  R6            2.4.0   2019-02-14 [1] CRAN (R 3.5.3)
#>  Rcpp          1.0.2   2019-07-25 [1] CRAN (R 3.5.3)
#>  remotes       2.1.0   2019-06-24 [1] CRAN (R 3.5.3)
#>  rlang         0.4.0   2019-06-25 [1] CRAN (R 3.5.3)
#>  rmarkdown     1.14    2019-07-12 [1] CRAN (R 3.5.3)
#>  RPostgres   * 1.1.1   2018-05-06 [1] CRAN (R 3.5.3)
#>  rprojroot     1.3-2   2018-01-03 [1] CRAN (R 3.5.3)
#>  sessioninfo   1.1.1   2018-11-05 [1] CRAN (R 3.5.3)
#>  stringi       1.4.3   2019-03-12 [1] CRAN (R 3.5.3)
#>  stringr       1.4.0   2019-02-10 [1] CRAN (R 3.5.3)
#>  testthat      2.2.1   2019-07-25 [1] CRAN (R 3.5.3)
#>  tibble        2.1.3   2019-06-06 [1] CRAN (R 3.5.3)
#>  usethis       1.5.1   2019-07-04 [1] CRAN (R 3.5.3)
#>  vctrs         0.2.0   2019-07-05 [1] CRAN (R 3.5.3)
#>  withr         2.1.2   2018-03-15 [1] CRAN (R 3.5.1)
#>  xfun          0.8     2019-06-25 [1] CRAN (R 3.5.3)
#>  yaml          2.2.0   2018-07-25 [1] CRAN (R 3.5.1)
#>  zeallot       0.1.0   2018-01-28 [1] CRAN (R 3.5.3)
#> 
#> [1] C:/Users/[user]/Documents/R/win-library/3.5
#> [2] C:/Program Files/R/R-3.5.1/library
Created on 2019-08-07 by the reprex package (v0.3.0)

```

Any clues as to what is going on? Let me know if more info is needed.

**Comment by krlmlr** [comment] 2019-12-17 21:38
Thanks. Is this a duplicate of #194? This is fixed in the development version, which will hit CRAN very soon.

**Closed** 2020-12-26 04:59 UTC
